name: Playwright Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run tests with HTML report
      run: |
        pytest --html=reports/report.html --self-contained-html

    - name: Upload test report artifact
      uses: actions/upload-artifact@v3
      with:
        name: pytest-html-report
        path: reports/report.html
